services:
  web:
    build: .
    container_name: raahat_web

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped

  telegram:
    build: .
    container_name: raahat_telegram

    command: python run_bot.py

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped
